export const BOOKS = [
    {
        author: 'Eduardo Galeano',
        bookId: 16,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 6,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/galeanoAbrazos.png?alt=media&token=9ec4be3c-971f-459e-a28d-a6907d0995f7',
        length: 272,
        price: 7,
        releasedDate: '04/14/2006',
        stars: 4,
        stock: 54,
        title: 'El libro de los abrazos',
    },
    {
        author: 'Walter Isaacson',
        bookId: 10,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 1,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/steveJobs.png?alt=media&token=a4b7068e-d2d8-45df-bdb8-634a3bba7016',
        length: 656,
        price: 9,
        releasedDate: '10/24/2011',
        stars: 3,
        stock: -6,
        title: 'Steve Jobs: The Exclusive Biography',
    },
    {
        author: 'Msashi Kishimoto',
        bookId: 19,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 7,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/naruto.png?alt=media&token=a911a11c-5d04-4316-aa00-2de62830b334',
        length: 192,
        price: 6,
        releasedDate: '07/13/2011',
        stars: 4,
        stock: 11,
        title: 'Naruto, Vol. 1: Uzumaki Naruto',
    },
    {
        author: 'Nelson Mandela',
        bookId: 9,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 1,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/nelsonMandela.png?alt=media&token=43b2ecd5-5337-4e96-a56c-41040b972859',
        length: 656,
        price: 8,
        releasedDate: '10/01/1995',
        stars: 5,
        stock: 0,
        title: 'Long Walk to Freedom: The Autobiography of Nelson Mandela',
    },
    {
        author: 'Rainbow Rowell',
        bookId: 23,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 5,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/eleanorAndPark.png?alt=media&token=07673b6e-ccb4-4418-b7ac-7fbcc25b657d',
        length: 320,
        price: 15,
        releasedDate: '02/26/2013',
        stars: 5,
        stock: 7,
        title: 'Eleanor & Park',
    },
    {
        author: 'Eduardo Galeano',
        bookId: 13,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 3,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/galeano.png?alt=media&token=a2ce51e3-3b7e-48b8-be3b-74025abab322',
        length: 395,
        price: 7,
        releasedDate: '02/03/1998',
        stars: 5,
        stock: 15,
        title: 'Patas arriba: La escuela del mundo al revéz',
    },
    {
        author: 'Edith Eva Eger',
        bookId: 5,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 1,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/thechoice.png?alt=media&token=7a041132-adef-441f-b8e9-20524df5ce77',
        length: 320,
        price: 13,
        releasedDate: '02/01/2019',
        stars: 5,
        stock: 24,
        title: 'The Choice',
    },
    {
        author: 'Tara Westover',
        bookId: 1,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 1,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/educated.png?alt=media&token=77d0aaa8-ee7c-42ca-aa3f-a64a6e2dcff2',
        length: 352,
        price: 12,
        releasedDate: '11/27/2018',
        stars: 5,
        stock: 51,
        title: 'Educated',
    },
    {
        author: 'Trevor Noah',
        bookId: 11,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 3,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/trevorNoah.png?alt=media&token=2d07ca1f-c0cf-4449-8f08-8e71cef4cf79',
        length: 264,
        price: 8,
        releasedDate: '11/15/2016',
        stars: 4,
        stock: 20,
        title: 'Born a Crime: Stories from a South African Childhood',
    },
    {
        author: 'Akira Toriyama',
        bookId: 21,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 7,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/dragonBall.png?alt=media&token=d0b9fae2-abcd-42a3-b558-4f4b1c6bf5d6',
        length: 192,
        price: 7,
        releasedDate: '03/01/2003',
        stars: 5,
        stock: 101,
        title: 'Dragon Ball, Vol. 1',
    },
    {
        author: 'Suzanne Collins',
        bookId: 24,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 5,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/hungerGames.png?alt=media&token=a3d057d7-7f60-4e68-8344-ee9058ae7d7a',
        length: 374,
        price: 12,
        releasedDate: '07/01/2010',
        stars: 5,
        stock: 14,
        title: 'The Hunger Games',
    },
    {
        author: 'Walt Whitman',
        bookId: 17,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 6,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/whitman.png?alt=media&token=3aa08333-64cd-4e4b-9dcf-2153358dd4bf',
        length: 608,
        price: 6,
        releasedDate: '04/01/1998',
        stars: 3,
        stock: 4,
        title: 'Complete Poems of Whitman',
    },
    {
        author: 'Jonathan Safran Foer',
        bookId: 8,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 2,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/extremely.png?alt=media&token=745c7cec-3ce0-485f-b82f-46e949ce9c0c',
        length: 368,
        price: 16,
        releasedDate: '04/06/2006',
        stars: 5,
        stock: 82,
        title: 'Extremely Loud and Incredibly Close',
    },
    {
        author: 'Greame Simsion',
        bookId: 4,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 2,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/rosie.png?alt=media&token=b585ccc5-e9c9-4fde-a925-792b9d0413ca',
        length: 395,
        price: 14,
        releasedDate: '02/02/2014',
        stars: 5,
        stock: 46,
        title: 'The Rosie Project',
    },
    {
        author: 'Jorge Luis Borges',
        bookId: 14,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 6,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/borges.png?alt=media&token=1af16aea-283f-4df6-b272-7e41a845e622',
        length: 348,
        price: 20,
        releasedDate: '01/01/1972',
        stars: 3,
        stock: 5,
        title: 'Selected Poems 1923-1967',
    },
    {
        author: 'Robert Kirkman',
        bookId: 20,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 7,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/walkingDead.png?alt=media&token=4454befd-36d5-4990-88ef-562e3935011c',
        length: 144,
        price: 5,
        releasedDate: '02/19/2013',
        stars: 4,
        stock: 100,
        title: 'The Walking Dead, Vol. 1: Days Gone Bye',
    },
    {
        author: 'Quino',
        bookId: 18,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 7,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/mafalda.png?alt=media&token=74cc2eeb-50ab-4251-8f73-9c9b8647d505',
        length: 659,
        price: 70,
        releasedDate: '10/01/2020',
        stars: 5,
        stock: 0,
        title: 'Toda Mafalda',
    },
    {
        author: 'John Green',
        bookId: 6,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 5,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/lookingforalaska.png?alt=media&token=a557da13-c334-41be-a460-0126912be499',
        length: 221,
        price: 10,
        releasedDate: '03/03/2005',
        stars: 5,
        stock: 0,
        title: 'Looking for Alaska',
    },
    {
        author: 'Angie Thomas',
        bookId: 22,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 5,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/theHateUGive.png?alt=media&token=5aae351c-973e-4d16-b8bb-4297097da539',
        length: 464,
        price: 9,
        releasedDate: '02/28/2017',
        stars: 4,
        stock: 30,
        title: 'The Hate U Give',
    },
    {
        author: 'Yuval Noah Harari',
        bookId: 12,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 3,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/harari.png?alt=media&token=98dea81a-0daf-43cb-ad4b-bba5e298f3d5',
        length: 455,
        price: 15,
        releasedDate: '02/21/2017',
        stars: 4,
        stock: 0,
        title: 'Homo Deus: A Brief History of Tomorrow',
    },
    {
        author: 'Jodi Picoult',
        bookId: 2,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 2,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/sgt.PNG?alt=media&token=f71825f8-b6c5-4331-9176-52996ebc758b',
        length: 528,
        price: 12,
        releasedDate: '04/11/2017',
        stars: 5,
        stock: 88,
        title: 'Small Great Things',
    },
    {
        author: 'Lewis Carroll',
        bookId: 27,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 4,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/alice.png?alt=media&token=98c4a974-8431-44f5-a2fa-8f409f670cdf',
        length: 120,
        price: 30,
        releasedDate: '10/29/2011',
        stars: 5,
        stock: 20,
        title: "Alice's Adventures in Wonderland",
    },
    {
        author: 'Fernadno Pessoa',
        bookId: 15,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 6,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/pessoa.png?alt=media&token=5ccc8ed8-6bc5-4733-8e2e-d62767de6284',
        length: 390,
        price: 12,
        releasedDate: '11/01/2007',
        stars: 3,
        stock: 100,
        title: 'The Selected Prose of Fernando Pessoa',
    },
    {
        author: 'J. M. Barrie',
        bookId: 26,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 4,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/peterPan.png?alt=media&token=2992ce4b-727b-4765-9f55-d74ba5e3f200',
        length: 168,
        price: 30,
        releasedDate: '02/02/2018',
        stars: 5,
        stock: 40,
        title: 'Peter Pan',
    },
    {
        author: 'María Inés Falconi',
        bookId: 28,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 4,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/caidosDelMapa.png?alt=media&token=0b12e770-179b-436b-8a94-54157612fce9',
        length: 111,
        price: 6,
        releasedDate: '03/05/1995',
        stars: 4,
        stock: 17,
        title: 'Caídos del Mapa',
    },
    {
        author: 'John Carreyrou',
        bookId: 3,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 3,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/badblood.png?alt=media&token=d66f0279-05c3-4f57-9e11-6b0e59b4cb7e',
        length: 368,
        price: 12,
        releasedDate: '07/11/2019',
        stars: 5,
        stock: 127,
        title: 'Bad Blood',
    },
    {
        author: 'Louisa May Alcott',
        bookId: 7,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 2,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/littlewomen.png?alt=media&token=599df89c-0af0-4a54-a30b-e395b21b6087',
        length: 777,
        price: 12,
        releasedDate: '06/01/2013',
        stars: 5,
        stock: 25,
        title: 'Little Women',
    },
    {
        author: 'Serrano Tomas',
        bookId: 25,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        genreId: 4,
        img: 'https://firebasestorage.googleapis.com/v0/b/bookstore-69243.appspot.com/o/salfon.png?alt=media&token=fce7a3f1-7435-46c0-a360-266055f08add',
        length: 30,
        price: 8,
        releasedDate: '04/05/2001',
        stars: 5,
        stock: 50,
        title: 'Salfon, el limpiador de tejados',
    },
];
